-- CREATE TABLE tasks (
-- id serial primary key,
-- task varchar(180),
-- due date
-- );
--
-- UPDATE tasks
-- SET completed = TRUE
-- WHERE id = 66;
-- 'DELETE FROM tasks ' +
--              'WHERE id = ($1)', [id],
